### ISSUE TITLE
Handling Element prefix in Akana Platform

### ISSUE THREAD

**Issue by robincher** [akanainc/freemarker-activity#3]
Hi guys,

Is there any quick way to handle element defined prefix? Somehow i encountered error whenever i defined a prefix within in the xml response.

Sample XML Output

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Body>
      <element xmlns:tns="http://www.sample.com">
         <name>Rob</name>    
      </element>
   </soap:Body>
</soap:Envelop>
```

Freemarker Template 

```
<#ftl 
  ns_prefixes={
  "soap":"http://www.w3.org/2003/05/soap-envelope"
  , "tns":"http://www.sample.com"
  }
>
  
{
  "result" : "${message.contentAsXml["soap:Envelope"]["soap:Body"]["tns:element"]["name"]}"
  }
```

The output should be 
```
{
  "result" : "Rob"
}
```

**Comment by igoldsmith** [comment]
I could be wrong, but I don’t think that’s valid XML.  The <name> element isn’t part of a namespace, plus you’re missing the trailing e on the close of Envelope.  Maybe try:

 

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">

   <soap:Body>

      <element xmlns:tns="http://www.sample.com">

         <tns:name>Rob</tns:name>    

      </element>

   </soap:Body>

</soap:Envelope>

 

With this template:

 

<#ftl 

  ns_prefixes={

  "soap":"http://www.w3.org/2003/05/soap-envelope"

  , "tns":"http://www.sample.com"

  }

> 

  

{

  "result" : "${message.contentAsXml["soap:Envelope"]["soap:Body"]["tns:element"]["tns:name"]}"

  }

 

I can’t guarantee that this will work.  Have you tried the test tool we include in the Git repository?  It might make it easier to try out various templates with various different content forms.

 

Ian

**Comment by robincher** [comment]
Hi Ian,

Thanks for the prompt reply. Am i right to say that multiple prefixes are supported? 

Will test this out further and share with you the results.

**Comment by akanadocs** [comment]
I think so.  I believe we link to the Freemarker docs from the Github page.  Those docs are a bit hard to navigate, but there's plenty of good info there.

--
Ian Goldsmith - +1 310 612 5649

On May 12, 2017, at 11:14 AM, Robin Cher <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ian,

Thanks for the prompt reply. Am i right to say that multiple prefixes are supported?

Will test this out further and share with you the results.

**Comment by robincher** [comment]
Hi Ian,

I think the request wasn't well-formed initially so i get back to the origin and educate them to construct it in a proper convention. Nonetheless, i close this issue,and probably i can look into freemarker forums for general questions, and keep it Akana's specific here.  Thanks!
